# backend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходный код
COPY . .

# Устанавливаем Prisma CLI
RUN npx prisma generate

EXPOSE 3001

CMD ["npm", "run", "dev"]